version: "3"

services:
  test_runner:
    build: .
    image: pytest_runner
    container_name: pythest_runner_works
    environment:
      - ENV=INSIDE_DOCKER True
    volumes:
      - .:/web_tests/
